import React from 'react';
import { useParams } from 'react-router-dom';

// Import all program components
import AIMLAgricultureProgram from './programs/AIMLAgricultureProgram';
import GeneralAgricultureProgram from './programs/GeneralAgricultureProgram';
import RoboticsProgram from './programs/RoboticsProgram';
import CybersecurityProgram from './programs/CybersecurityProgram';
import DataScienceProgram from './programs/DataScienceProgram';
import IoTProgram from './programs/IoTProgram';
import GameDevelopmentProgram from './programs/GameDevelopmentProgram';
import ElectricVehicleProgram from './programs/ElectricVehicleProgram';
import HumanComputerInteractionProgram from './programs/HumanComputerInteractionProgram';
import AIBusinessProgram from './programs/AIBusinessProgram';
import AICybersecurityProgram from './programs/AICybersecurityProgram';
import AIBlockchainProgram from './programs/AIBlockchainProgram';
import AgricultureRoboticsProgram from './programs/AgricultureRoboticsProgram';
import AgriEntrepreneurshipProgram from './programs/AgriEntrepreneurshipProgram';

import HydroponicsFarmingProgram from './programs/HydroponicsFarmingProgram';
import FermentationTechnologyProgram from './programs/FermentationTechnologyProgram';
import VaccineTechnologyProgram from './programs/VaccineTechnologyProgram';
import MedicalCodingProgram from './programs/MedicalCodingProgram';
import IPLawProgram from './programs/IPLawProgram';

// Import new program components
import AgricultureDronesProgram from './programs/AgricultureDronesProgram';
import AdvancedTechnologiesAgricultureProgram from './programs/AdvancedTechnologiesAgricultureProgram';
import GenerativeAIProgram from './programs/GenerativeAIProgram';
import AIBiologicalSciencesProgram from './programs/AIBiologicalSciencesProgram';
import AILawProgram from './programs/AILawProgram';
import AIMarketingProgram from './programs/AIMarketingProgram';
import ClinicalResearchRegulatoryAffairsProgram from './programs/ClinicalResearchRegulatoryAffairsProgram';
import DigitalForensicsProgram from './programs/DigitalForensicsProgram';
import BioentrepreneurshipProgram from './programs/BioentrepreneurshipProgram';
import AIDesigningTechnologyProgram from './programs/AIDesigningTechnologyProgram';
import AIArtsProgram from './programs/AIArtsProgram';
import ARVRXRDevelopmentProgram from './programs/ARVRXRDevelopmentProgram';
import VirtualAugmentedRealityEngineeringProgram from './programs/VirtualAugmentedRealityEngineeringProgram';
import AIManagementCertificateProgram from './programs/AIManagementCertificateProgram';
import PrecisionAgricultureProgram from './programs/PrecisionAgricultureProgram';
import AIManagementStudiesProgram from './programs/AIManagementStudiesProgram';
import DoctoralPrograms from './programs/DoctoralPrograms';
import PostdoctoralPrograms from './programs/PostdoctoralPrograms';
import ARVRTechnologyProgram from './programs/ARVRTechnologyProgram';
// import ProLearnProgram from './programs/ProLearnProgram'; // Removed - using external link

const ProgramRouter: React.FC = () => {
  const { programSlug } = useParams<{ programSlug: string }>();
  
  console.log('ProgramRouter: programSlug =', programSlug);

  // Program mapping based on actual slugs generated by ProgramCard component
  const programComponents: { [key: string]: React.ComponentType } = {
    // Precision Agriculture Programs
    'precision-agriculture': PrecisionAgricultureProgram,
    'agriculture-drones': AgricultureDronesProgram,
    'hydroponics-farming': HydroponicsFarmingProgram,
    'advanced-technologies-agriculture': AdvancedTechnologiesAgricultureProgram,
    'agriculture-robotics': AgricultureRoboticsProgram,
    'ai-ml-agriculture': AIMLAgricultureProgram,
    'agriculture': GeneralAgricultureProgram,
    'agri-entrepreneurship': AgriEntrepreneurshipProgram,
    
    // AI & Robotics Programs
    'robotics': RoboticsProgram,
    'generative-ai': GenerativeAIProgram,
    'ai-blockchain': AIBlockchainProgram,
    'data-science': DataScienceProgram,
    'ai-biological-sciences': AIBiologicalSciencesProgram,
    'ai-cybersecurity': AICybersecurityProgram,
    'cybersecurity': CybersecurityProgram,
    
    // AI & Business Programs
    'ai-business': AIBusinessProgram,
    'ai-management-studies': AIManagementStudiesProgram,
    'ai-law': AILawProgram,
    'ip-law': IPLawProgram,
    'ai-marketing': AIMarketingProgram,
    
    // Healthcare & Life Sciences
    'clinical-research-regulatory-affairs': ClinicalResearchRegulatoryAffairsProgram,
    'medical-coding': MedicalCodingProgram,
    'digital-forensics': DigitalForensicsProgram,
    'fermentation-technology': FermentationTechnologyProgram,
    'vaccine-technology': VaccineTechnologyProgram,
    'bioentrepreneurship': BioentrepreneurshipProgram,
    
    // AI & Creative Technologies
    'ai-designing-technology': AIDesigningTechnologyProgram,
    'ai-arts': AIArtsProgram,
    
    // Emerging Technologies & Smart Systems
    'reality-architect-master-of-arvrxr-development': ARVRXRDevelopmentProgram,
    'virtual-vanguard-master-in-virtual-augmented-reality-engineering': VirtualAugmentedRealityEngineeringProgram,
    'electric-vehicle': ElectricVehicleProgram,
    'iot': IoTProgram,
    'human-computer-interaction': HumanComputerInteractionProgram,
    
    // Homepage Specific Programs
    'ai-management-certificate': AIManagementCertificateProgram,
    'ar-vr-technology': ARVRTechnologyProgram,
    
    // Doctoral & Postdoctoral Programs
    'doctoral-programs': DoctoralPrograms,
    'postdoctoral-programs': PostdoctoralPrograms,
    
    // ProLearn Program - using external link
    // 'prolearn': ProLearnProgram,
    
    // Additional consolidated mappings
    'game-development': GameDevelopmentProgram,
    'data-analytics': DataScienceProgram
  };

  // Get the component for the requested program
  const ProgramComponent = programComponents[programSlug || ''];
  

  if (!ProgramComponent) {
    return (
      <div style={{ 
        minHeight: '100vh', 
        backgroundColor: '#f8f9fa', 
        padding: '20px',
        fontFamily: 'Arial, sans-serif'
      }}>
        <div style={{
          maxWidth: '800px',
          margin: '0 auto',
          backgroundColor: 'white',
          padding: '40px',
          borderRadius: '8px',
          boxShadow: '0 2px 10px rgba(0,0,0,0.1)',
          textAlign: 'center'
        }}>
          <h1 style={{ color: '#dc3545', marginBottom: '20px' }}>Program Not Found</h1>
          <p style={{ color: '#6c757d', marginBottom: '30px' }}>
            The requested program "{programSlug}" could not be found.
          </p>
          <a href="/programs" style={{
            backgroundColor: '#007bff',
            color: 'white',
            padding: '10px 20px',
            textDecoration: 'none',
            borderRadius: '5px'
          }}>
            Back to Programs
          </a>
        </div>
      </div>
    );
  }

  try {
    return <ProgramComponent />;
  } catch (error) {
    console.error('Error rendering program component:', error);
    return (
      <div style={{ 
        minHeight: '100vh', 
        backgroundColor: '#f8f9fa', 
        padding: '20px',
        fontFamily: 'Arial, sans-serif'
      }}>
        <div style={{
          maxWidth: '800px',
          margin: '0 auto',
          backgroundColor: 'white',
          padding: '40px',
          borderRadius: '8px',
          boxShadow: '0 2px 10px rgba(0,0,0,0.1)',
          textAlign: 'center'
        }}>
          <h1 style={{ color: '#dc3545', marginBottom: '20px' }}>Error Loading Program</h1>
          <p style={{ color: '#6c757d', marginBottom: '30px' }}>
            There was an error loading the program page. Please try again.
          </p>
          <a href="/programs" style={{
            backgroundColor: '#007bff',
            color: 'white',
            padding: '10px 20px',
            textDecoration: 'none',
            borderRadius: '5px'
          }}>
            Back to Programs
          </a>
        </div>
      </div>
    );
  }
};

export default ProgramRouter;
